name: "Context Examples"

on: ['push']

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:            
            - name: "My Step"
              run: |
                echo "Hello $MY_ACTION"
                echo "Hello ${{ github.actor }}"
              env:
                MY_ACTION: ${{ github.action }}
